### ISSUE TITLE
Logger for dev env

### ISSUE THREAD

**Issue by ihorkatkov** [fremantle-industries/workbench#68]
Hey @rupurt.
Thanks for the outstanding library.
I'm wondering, any specific reason to not have default logger for dev env?

**Comment by rupurt** [comment]
🍻 I've been super slammed with work so haven't had much time to improve `workbench` recently. Hopefully you find it useful 😄 and feel free to ping me with any more questions to help you get up and running.

As for the default logger, you should have one in `dev`. Is this not working? https://github.com/fremantle-industries/workbench/blob/master/config/config.exs#L31

**Comment by ihorkatkov** [comment]
No, it's not. If you are running it locally, you don't see logging info. I enabled `:console` only in the dev config. 
```elixir
config :logger,
  backends: [:console],
  utc_log: true
```
What about to add `dev.personal.exs` which will be ignored by git? Or something similar?

I'm thinking about the approach of how to use `workbench` with the possibility to override its configuration and don't lose the possibility to pull updates from the repo...

WDYT?

**Comment by rupurt** [comment]
Fixed in https://github.com/fremantle-industries/workbench/commit/88ba715d484e126d7e7a15f171e94820b8cb1dbd
